### PR TITLE
Enable Defining A Custom Thousand Separator Format

### PR DESCRIPTION
**Pull request by ahmedmsvb**
Java Script parseFloat method ignores comma when parsing a string number
For some locales, the amount is written in format 1,234.56
The above will not parse correctly unless ynab-buddy was instructed with the correct separator format

### CODE REVIEW

**Comment by nielsmaerten** [comment]
Thanks for spotting this! 

I'll take a closer look at this later, but so far I've added another test in branch fix/parse-amounts.
This test tries parsing using a number of different formats, which seems to work nicely with your fix.

For backwards compatibility, we'll have to use the 'old' way of parsing when neither decimal nor thousand separators are defined though.

**Comment by ahmedmsvb** [comment]
Glad that it worked with all the new tests!
Let me know if I can help in finalizing this PR.

1. And, of course, thanks for this great and useful repo ;)

**Review by nielsmaerten — APPROVED** [review]
Hi @ahmedmsvb 
I made a few minor changes:

- additional test to assert correct parsing of a bunch of different formats
- added the separator options to the default config file
- fallback to the original behavior if no separator is defined. this will allow existing users to upgrade without having to change their config file
- strip out non-number characters (eg "€ 1234.56" => "1234.56")

**Comment by ahmedmsvb** [comment]
Hi @nielsmaerten 

Looks more robust now.
I ran the new test locally with negative values as well and it passed (don't think we need to duplicate the test with negative numbers)

The decimals fallback is a good idea as long as it is mentioned in the docs

**Comment by nielsmaerten** [comment]
Updated the docs: it now says leaving out the decimal separator isn't recommended. But that if you **do** skip it, the tool will try to "auto-detect" the separator. (Went with "auto-detect" bc I don't want the docs to be too technical).

Since the settings for decimal and thousands separators will now appear in the default config file (the one that gets created when ynab-buddy runs for the first time), we can already be pretty sure people will fill in this value.

**Pull request merged**
